### ISSUE TITLE
Image?

### ISSUE THREAD

**Issue by tfraley** [NodeBB-Community/nodebb-plugin-recent-cards#1]
Any way to make the recent card pull the image we used to create the category?

**Comment by psychobunny** [comment]
I think this should already work (but I haven't tested it): https://github.com/psychobunny/nodebb-plugin-recent-cards/blob/master/static/templates/partials/nodebb-plugin-recent-cards/header.tpl#L16

**Comment by tfraley** [comment]
Doesn't seem to be working for me,
The category  "Vaping", You can see there is a smoke image in the category list 
However, in the recent topics section topic "testing222" it does not show an image..

Am I missing something? Did I over look an enable or something 

http://forum.lifewithtech.net:4567

**Comment by psychobunny** [comment]
Fixed in https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/pull/14
