### ISSUE TITLE
Opacity and link

### ISSUE THREAD

**Issue by frankdiox** [NodeBB-Community/nodebb-plugin-recent-cards#17]
I updated to the last version (0.1.0) and found that now there is no opacity on hover and the link only works if you click on the text, not on the whole card. Is that the expected behavior in the new version?

**Comment by frankdiox** [comment]
Also, looks like the first time the forum loads it doesn't display this plugin. It's displayed when clicking in the home link afterwards. You can check this forum [here](https://community.onsen.io/).

**Comment by frankdiox** [comment]
@yariplus @psychobunny  Actually, I noticed one more weird thing. If you hover the card entering from the bottom left side (where the icon is) then everything is clickable. Otherwise is not.

**Comment by yariplus** [comment]
Was the whole card clickable before?

I personally don't like the whole card clickable, but if that is the expected behavior I will change it to be so.

**Comment by frankdiox** [comment]
It was. At least in the previous version I had also with opacity hover. For me that's the expected behavior but of course other people may have different opinion :sweat_smile:

**Comment by yariplus** [comment]
Yeah, I agree. I'm going to fix it/change it back.

**Comment by yariplus** [comment]
I can't publish this package to NPM.

@psychobunny

**Comment by frankdiox** [comment]
@yariplus @psychobunny Just reminding... can this be merged? Thanks!

**Comment by psychobunny** [comment]
Forgot to close this issue, this was merged some time ago :) thanks
