### ISSUE TITLE
Hi, this plugin doesn't work on NodeBB v1.3.0

### ISSUE THREAD

**Issue by hao-lee** [NodeBB-Community/nodebb-plugin-recent-cards#21]
Hi,
Yesterday I upgraded this plugin to v0.2.4, but I found it didn't work. I'm sure that v0.2.3 is OK, but v0.2.4 has some problems.
Thanks.

**Comment by Zelakto** [comment]
I'm also having this issue.

**Comment by psychobunny** [comment]
latest works on nodebb 1.4.0 now - for 1.3.0 it's fine to stick to 0.2.4

**Comment by hao-lee** [comment]
@psychobunny Thanks for your hard work!
