### ISSUE TITLE
Cards show Invalid Date

### ISSUE THREAD

**Issue by KunSergey** [NodeBB-Community/nodebb-plugin-recent-cards#23]
I have tried to uninstall and re-install the plugin but it didn't fix this bug. 
This happens when the last message older than 2 days.
Nodebb version is v1.4.3.
Thx

**Comment by KunSergey** [comment]
Library.js[Line 80] https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/blob/master/library.js#L80

posts[p].topic didn't have property timestampISO - it stay in posts[p] object 

```topics.topics.push(topic); ``` 
need replace to 
```topic.timestampISO = posts[p].timestampISO; topics.topics.push(topic);```

Thx

**Comment by barisusakli** [comment]
@psychobunny need new version 👼

**Comment by RoiEXLab** [comment]
This should be reopened because of https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/commit/9e1fd238fa71c79d609b62d7d5c49ed25d37b221

**Comment by psychobunny** [comment]
It's closed in the `develop` branch if you are tracking `develop` for NodeBB. If you're using 1.4.3/4 you should use 0.3.1 for this plugin

**Comment by RoiEXLab** [comment]
Ah ok... Thanks anyways...
