### ISSUE TITLE
Cards not visible

### ISSUE THREAD

**Issue by PongoPygmaeus** [NodeBB-Community/nodebb-plugin-recent-cards#24]
Just upgraded to NodeBB 1.4.3 and Recent Cards 0.3.1
The cards aren't visible anymore. Don't know anything beyond that, no errors.
Tried multiple browsers, reinstalling, etc. Prior version of persona was v4.1.93 and cards was 0.2.something (8?).

Edit: rolling back to 0.2.8 fixed it

**Comment by psychobunny** [comment]
Thanks, 0.2.8 is the right version for NodeBB 1.4.3
Recent cards 0.3.1 actually is for the next version we release... I'll fix that

**Comment by michaelpfaff** [comment]
Hi psychobunny. I posted this same issue on NodeBB forum. I'm on NodeBB 1.4.4. Should I use an older version of Recent Cards? Right now I'm running 0.3.2 and nothing is showing with no errors also.
