### ISSUE TITLE
recent cards not working since upgrade to nodebb 1.4.4 / recent cards 0.3.2

### ISSUE THREAD

**Issue by joolswills** [NodeBB-Community/nodebb-plugin-recent-cards#25]
Since updating to nodebb v1.4.4 the recent cards are not showing. The plugin is also updated to 0.3.2.

I noticed another user has the same problem also https://community.nodebb.org/topic/10315/recent-cards-not-working-after-1-4-4-upgrade

many thanks.

**Comment by michaelpfaff** [comment]
Thanks, @joolswills. There was also a user with a closed ticket using v1.4.3 that experienced a similar issue.

**Comment by michaelpfaff** [comment]
v0.3.1 works okay with v1.4.4

**Comment by sohrabafard** [comment]
👍

**Comment by joolswills** [comment]
I just updated to v1.4.5 and recent cards v0.3.2 doesn't work with it either - have disabled for now rather than rolling back to v0.3.1

**Comment by a632079** [comment]
+1

**Comment by ScaniaTV** [comment]
+1
Yup, I have the same issue on v1.4.5.

**Comment by zamberjo** [comment]
+1

**Comment by sohrabafard** [comment]
+1 
nodebb 1.4.6

**Comment by spwolf** [comment]
+1
same here with 1.4.5

**Comment by a632079** [comment]
Something wrong when update to 1.4.6.
see at https://github.com/NodeBB/nodebb-theme-persona/issues/358

**Comment by spwolf** [comment]
upgraded to 1.4.6 and tried to downgrade plugin to 0.3.1 but still does not work.

**Comment by psychobunny** [comment]
Sorry guys, I kept thinking that this would be resolved when we're going to release 1.5.0 ... and it ended up taking a few months longer for us to release that version than I thought.

In any case, just tested plugin@0.4.0 on nbb@1.5.0 and looks good to go. Downgrade to 0.3.1 for < 1.5.0 

😄
