### ISSUE TITLE
Displays topics even when the category is disabled.

### ISSUE THREAD

**Issue by ghost** [NodeBB-Community/nodebb-plugin-recent-cards#28]
I noticed that if you create category and disable it or set permissions so only global moderators can access the category, then you go create topics in that category they are still getting displayed in this plugin.
Normally, you only want to display topics to guests, registered users, etc are when you allow permissions and the category is enabled. I wanted my topics hidden from guests, etc until I was ready, which work is fine in the normal category list, but if you have this plugin activated they get displayed and are visible regardless of the cat permission and status of the category.

**Comment by barisusakli** [comment]
`topics:read` privilege controls the visibility of the topics not category access
