### ISSUE TITLE
Nover show up for NodeBB 1.10.1

### ISSUE THREAD

**Issue by unbug** [NodeBB-Community/nodebb-plugin-recent-cards#31]
I've upgrade to NodeBB 1.10.1, somehow the card just never show up. I uninstalled and re-installed issue remain.

**Comment by mohammadhassan99** [comment]
Yeah it is not working. Please reproduce 🙏

**Comment by spwolf** [comment]
same here...

**Comment by psychobunny** [comment]
:+1: this broke in 1.10.1, I'm going to address this one ASAP (likely tomorrow), but in the meantime you can undo [this change](https://github.com/NodeBB/NodeBB/commit/04d31fe1d4f09fef60ee0c07a3982d30fd12992c#diff-43745df65125f2c8341f0285e4e631ce) in nodebb core without any ill effects:

`git revert 04d31fe1d4f09fef60ee0c07a3982d30fd12992c`

**Comment by sohrabafard** [comment]
Hi please fix it
This is a great plugin 😍

**Comment by sohrabafard** [comment]
Up

**Comment by sohrabafard** [comment]
@psychobunny
Please fix it

**Comment by mohammadhassan99** [comment]
@psychobunny Please reproduce 🙏

**Comment by spwolf** [comment]
> 👍 this broke in 1.10.1, I'm going to address this one ASAP (likely tomorrow), but in the meantime you can undo [this change](https://github.com/NodeBB/NodeBB/commit/04d31fe1d4f09fef60ee0c07a3982d30fd12992c#diff-43745df65125f2c8341f0285e4e631ce) in nodebb core without any ill effects:
> 
> `git revert 04d31fe1d4f09fef60ee0c07a3982d30fd12992c`

hopefully you will find time to address this soon... many thanks in advance!

**Comment by psychobunny** [comment]
Sorry everyone for the huge delay here, it's been a pretty busy past month or so for me 😄. Now that this plugin uses the widget system please place the widget under "Categories Header" to maintain the old behavior.

Also, it should now be a bit more compatible with other themes (mileage may vary), and a couple new features as it is now a widget. Thanks for your patience!
