### ISSUE TITLE
Bug when there is only 1 recent topic to display

### ISSUE THREAD

**Issue by jtsimoes** [NodeBB-Community/nodebb-plugin-recent-cards#36]
When there is only one recent topic, this little bar show up... I guess it's probably the beginning of a 'recent card', but I don't know how to fix it.
Hope you know how to do it!

![image](https://user-images.githubusercontent.com/34691647/47335396-ecb24a00-d682-11e8-8b44-f2f2be9b27e7.png)

**Comment by jtsimoes** [comment]
Up!

**Comment by combr** [comment]
Same bug here on nodebb 1.14.1 and recent-cards Installed 1.0.13 | Latest 1.0.13
![изображение](https://user-images.githubusercontent.com/65902828/87117973-95df1080-c269-11ea-90b8-bd8fdb7531ea.png)

I have a TWO topics now in this category, but second topic do not shown
![изображение](https://user-images.githubusercontent.com/65902828/87118270-77c5e000-c26a-11ea-9e45-8d6cfd937487.png)

If i disable "carousel view" in plugin settings, it looks as one card at the left 
![изображение](https://user-images.githubusercontent.com/65902828/87118228-58c74e00-c26a-11ea-9662-fe6fdf8e4cdb.png)
