### ISSUE TITLE
v1.0.9 - new bug

### ISSUE THREAD

**Issue by PointPubMedia** [NodeBB-Community/nodebb-plugin-recent-cards#43]
Just update this morning the plugin from nodebb and since that, I found a little issue.

All the pages in the forum that didn't display our widget we got the loading icon at the top right.

To troubleshoot the issue and make sure it come from the update of today, I move the widget to the "draft" zone and no more loading circle issue!

**Comment by PointPubMedia** [comment]
![image](https://user-images.githubusercontent.com/20915668/80640657-b9980600-8a31-11ea-928b-24403be796d8.png)

**Comment by barisusakli** [comment]
Loading icon at top right usually means a server side error as well. Were there any errors in nodebb logs?

**Comment by PointPubMedia** [comment]
thanks!  Stupid question, how do we upgrade our "plugin" when ppl like you update without releasing a new version ?

**Comment by PointPubMedia** [comment]
Thanks for the update.  The issue in case is now fixed but with this new update in other page except home page the caroussel is not working but we never got this issue before 1.0.9

![image](https://user-images.githubusercontent.com/20915668/80659277-7f8d2b00-8a56-11ea-86de-7804ab33857b.png)

**Comment by barisusakli** [comment]
@PointPubMedia @psychobunny published a new version.

My fix was only for the client side error you posted, but that fix would also stop the carousel from working if the recentCard data isn't loaded. So there might be another issue with your forum. When you are on a page that has the recent cards you can check `ajaxify.data.recentCards` in your browser it should be populated with some data.

**Comment by PointPubMedia** [comment]
In my screenshot, the recent card are all displayed instead of having the "sliding" effect.

**Comment by barisusakli** [comment]
@PointPubMedia @psychobunny informed my why this happens. We will work on a fix for this.
