### ISSUE TITLE
clicking cards does not take you last post you read

### ISSUE THREAD

**Issue by AliCihan** [NodeBB-Community/nodebb-plugin-recent-cards#46]
In 1.13.2, clicking recent cards takes you to the top of the topic instead of the new posts you haven't read...

**Comment by AliCihan** [comment]
how should this plugin function when posts in a thread are ordered from newer to older, rather than older to newer...

**Comment by barisusakli** [comment]
Seems like fixed in https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/commit/3391910bb1e38f607c7a047f06e45991050f1c4d#diff-ce149b6983a2d59efaa4ce383c3c0a5d
