### ISSUE TITLE
1.0.12 returns far too many topics if you disable the carousel 

### ISSUE THREAD

**Issue by adamxp12** [NodeBB-Community/nodebb-plugin-recent-cards#47]
Love this plugin but recently updated and found my homepage had 20 recent cards. which is very weird looking.

I can enable the carousel feature to make it one line like it should be but that adds the left/right buttons. Would much rather it was just the 4 recent cards like it was before as that's simple for users and just plain looks cleaner. the option to disable it exists for such a reason but right now its fairly broken.

I can see in commit 6708045b3f163f8593b13710bb1c5edea5f6c0f4 that a section of code that limited it to 4 cards when the carousel was disabled got moved and seems to have broken the hardcoded limit somehow? 

I think for many users who dont wish to use the carousel it should just be made to show just 4 like it used to. At the moment I am forced to use the carousel despite not wanting to.

**Comment by barisusakli** [comment]
@adamxp12 thanks for reporting
