### ISSUE TITLE
Next/Prev buttons bug/issue.

### ISSUE THREAD

**Issue by MotherShip808** [NodeBB-Community/nodebb-plugin-recent-cards#49]
https://i.imgur.com/9Dwcn3Q.png
small issue with the prev/next buttons. On my install (with forum theme nodebb-theme-oxide) the buttons are not properly aligned with the cards, they also take me to my forum's front page, causing the page to refresh. It does appear to do the normal prev/next actions as I do see the animations, however due to the refresh you cant actually ever leave the first 4 set of cards.

The alignment issue might be cause due to our forum width being increased from the default to 1440px.

**Comment by barisusakli** [comment]
The navigation issue will be fixed once you update to latest nodebb, it is fixed here if you want to apply it manually https://github.com/NodeBB/NodeBB/commit/6669b23d9aa8c6570841ebd660e205b087061d6a

You should be able to fix the alignment with some custom css
```
.bx-viewport {
   padding-left: 15px;
}
```

**Comment by MotherShip808** [comment]
we are currently on the latest version of nodebb 1.14.3, so I will def check out their manual fix. I appreciate the alignment fix as well, thanks!
