### ISSUE TITLE
Carousel Indicator Broken on Mobile

### ISSUE THREAD

**Issue by sm2x** [NodeBB-Community/nodebb-plugin-recent-cards#51]
NodeBB v1.16.1
nodebb-plugin-recent-cards v2.0.13 (psychobunny's)
nodebb-plugin-theme-persona v10.3.19

Recent cards carousel indicator is not showing properly on Mobile devices as opposed to desktops.

![image](https://user-images.githubusercontent.com/6595333/104951138-f0b5a980-59fc-11eb-85ca-d74132173ced.png)

**Comment by julianlam** [comment]
#27
