### ISSUE TITLE
 Max slides to show  didn't work properly 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB-Community/nodebb-plugin-recent-cards#52]
hi
recent card version Latest 2.0.16
 nodeBB v1.17.0-beta.0
when i checked  Enable Carousel Mode and  change the Max slides to show for carousel to 2 
Returns to initial settings after a few hours! 
it change  Max slides to show for carousel to 4
![20210306_135305](https://user-images.githubusercontent.com/37838903/110203465-accf1480-7e83-11eb-94dd-16bee7e0a1e0.jpg)
In this case, the width of the cards will be very small

 There is also another problem and that is when I do not use Carousel Mode, 
the cards are placed one below the other 
In this case, you can not access the  main menu by swipe You have to scroll to finish the box of cards then swipe to open the menu

**Comment by roghaye-m** [comment]
Does anyone have an opinion?

**Comment by barisusakli** [comment]
should be fixed in 2.0.17
