### ISSUE TITLE
Category exclusion for recent cards

### ISSUE THREAD

**Issue by AliCihan** [NodeBB-Community/nodebb-plugin-recent-cards#55]
is it possible to add a "category exclusion" setting to recent cards?

we do not want our "testing ground" topics to be seen there...

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/212712063-fa0cbe75-fa4d-4189-99e6-caf661d143db.png)
You can put all the category ids and leave out the one you don't want

**Comment by AliCihan** [comment]
> ![image](https://user-images.githubusercontent.com/2583394/212712063-fa0cbe75-fa4d-4189-99e6-caf661d143db.png) You can put all the category ids and leave out the one you don't want

hi baris , I have to include all sub and sub-sub categories separately, right? 
do you think having more than 100 categories listed would create a performance issue for recent cards?

**Comment by barisusakli** [comment]
Yeah you need to put everything, should be fine with 100 categories.
