### ISSUE TITLE
String Length and Text Overflowing

### ISSUE THREAD

**Issue by ayyilmaz** [NodeBB-Community/nodebb-plugin-recent-cards#57]
the plugin does not work nicely. It use all height and get the all text from the topic. Str length text limiting is not working currently. How can I solve the problem. I would like to set its appearence like nodebb forum. 

![image](https://user-images.githubusercontent.com/24845098/197057955-ead3480a-db09-4ced-b5ee-daa27de4da96.png)

**Comment by barisusakli** [comment]
What version of the plugin and nodebb are you using?

**Comment by ayyilmaz** [comment]
> 

NodeBB v2.5.7 and recent cards plugin version v3.1.2

**Comment by barisusakli** [comment]
Use nodebb-plugin-recent-cards@2.0.22, 3.1.2 is for nodebb 3.x and up.

**Comment by ayyilmaz** [comment]
> Use nodebb-plugin-recent-cards@2.0.22, 3.1.2 is for nodebb 3.x and up.

Ok thank you I will. Then will new versions of the plugin become compatible with nodeBB 3.X (Also I use 2.5.7 not 3.X)

**Comment by barisusakli** [comment]
As long as you use nodebb 2.5.7 stick with the 2.x versions of this pluign, once you upgrade to nodebb 3.x you can use the 3.1.2 version of this plugin.
