### ISSUE TITLE
Missing styles?

### ISSUE THREAD

**Issue by ht512512** [NodeBB-Community/nodebb-plugin-recent-cards#58]
I have installed the plugin on my test nodebb setup and it has the right behavior but not the right look. Looking at the debugger:inspector, It seems like none of the flex css from bootstrap is loaded. Also looked at the debugger:network to see if it ran into any 404 for css files, which it had not. 
The net result is that the it does not look right. I have attached the screenshot. Note the avatar placement and also the lack of justify-content-between for the category/when line.

BTW, I have added some custom css for card border and shadow that has no impact on this particular aspect. I have included it here for reference.
```
.slick-slide {
    border: 1px solid #aaa;
    box-shadow: 4px 4px #ddd;
    max-height: 150px;
    padding: 10px;
    margin-bottom: 5px;
}
.slick-list {
    padding-right: 20px;
    padding-left: 20px;
}
```

![Screenshot from 2022-10-30 17-27-39](https://user-images.githubusercontent.com/3441504/198909827-af62dcdc-7a2e-4e41-8162-433adeca096a.png)

**Comment by barisusakli** [comment]
nodebb version ? plugin version?

**Comment by barisusakli** [comment]
For nodebb 2.5.7 please use 2.0.23 of this plugin. 3.1.3 is meant for nodebb 3.x

**Comment by ht512512** [comment]
@barisusakli 
2.0.23 worked fine.
Thank you.
