### ISSUE TITLE
[Feature] Sort by topic publish date

### ISSUE THREAD

**Issue by Ghost-chu** [NodeBB-Community/nodebb-plugin-recent-cards#61]
Thanks for the awesome work!

We found an issue in running the community where we wanted the cards to show the most recent and newest topics posted, but we could only sort by Posts, but the newest Posts didn't always correspond to the newest Topics.

Would like to add a filter to sort by Topic post date on Recent Cards.

**Comment by barisusakli** [comment]
3.2.10 should allow sorting by topic create time, only if you leave the category ids blank though. Doing that requires adding a new sorted set to track topics by creation time in each category.

**Comment by Ghost-chu** [comment]
I still need the categoty ids filter, is it possible to use both the categoty ids filter and the topic creation time sort.

**Comment by barisusakli** [comment]
It will be in 3.7.0 > 

https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/commit/8f67e9974b1768c5cb766b772ec925519168e1da

**Comment by Ghost-chu** [comment]
Thank you for your time and dedication :)
