### ISSUE TITLE
Only partially displayed slide element is skipped when sliding

### ISSUE THREAD

**Issue by david-1904** [NodeBB-Community/nodebb-plugin-recent-cards#62]
Hi,

I just played with the Firefox Devtools and noticed it. I was able to reproduce it if I choose iPad iPadOS 14.7.1. Same for iPad Pro in Chrome Devtools. But I don't own an iPad so maybe it's not the case on a real device. You see only a part of the last slide element and when you slide, it is skipped and and the following element is in first place. I hope it is clear from the screenshots:

![2024-10-20 22_21_29-Window](https://github.com/user-attachments/assets/88a6e890-122b-449b-9511-bb4b6b80e538)

![2024-10-20 22_21_45-Window](https://github.com/user-attachments/assets/67221043-8a8f-453e-a071-2fb58a50390b)

**Comment by barisusakli** [comment]
published 3.3.2 I think it handles this viewport size better now
