### ISSUE TITLE
topic titles only show first few words

### ISSUE THREAD

**Issue by barisusakli** [NodeBB-Community/nodebb-plugin-recent-cards#8]
most of the time you cant tell what the topic is about 
![image](https://cloud.githubusercontent.com/assets/2583394/9868102/efb03262-5b42-11e5-8046-a7150e80cadd.png)

**Comment by liberaltech** [comment]
I was thinking the same thing. It would be cool if someone could switch the topic title and category font sizes so that we can read the entire topic title.
