### ISSUE TITLE
completly removes the categories from categories.tpl

### ISSUE THREAD

**Issue by barisusakli** [NodeBB-Community/nodebb-plugin-recent-cards#9]
doesnt happen all the time

![image](https://cloud.githubusercontent.com/assets/2583394/10270908/57c52728-6ace-11e5-9c04-a9757f9743f4.png)

**Comment by joolswills** [comment]
Just to follow on from https://github.com/NodeBB/NodeBB/issues/5296 - I also have this issue. Occurs quite often on my set-up (6 nodebb processes)

nodebb 1.4.2 (d5fb6dac38e4fb102dcd0a0256238019da1e84cf)
recent cards: 0.2.5
Database (mongo or redis) and it's version. Mongodb 3.2.11
Nginx nginx version: nginx/1.10.2 (from dotdeb.org)

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "REMOVED",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570, 4571, 4572],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "REMOVED",
        "database": "nodebb",
        "password": "REMOVED"
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
```

Sometimes I get the above, but with what looks like some templating tags showing also.

I have had to disable this plugin for now. Many thanks for your time.

**Comment by barisusakli** [comment]
Give it a try with the above fix.

**Comment by joolswills** [comment]
Thanks - what's the correct method to update to the git HEAD version of a plugin with nodebb ? Do I need to uninstall it via npm, and then manually install or ?

**Comment by psychobunny** [comment]
We've just published the latest version (0.2.7) so you can just go ahead and upgrade :)

**Comment by joolswills** [comment]
I did a couple of restarts and it seems ok - but I can't say for sure as it's not always triggered - but seems to be sorted. Many thanks.

**Comment by barisusakli** [comment]
Let us know if it happens again.
